server:
  port: 8808
jt808:
  built-components:
    request-handlers:
      enabled: true
    component-statistics:
      enabled: true
  protocol:
    max-frame-length: 1024
  server:
    port: 6808
    boss-thread-count: 0
    worker-thread-count: 0
    idle-state-handler:
      enabled: true
      reader-idle-time: 20m
      writer-idle-time: 0s # disabled
      all-idle-time: 0s # disabled
  msg-processor:
    executor-group:
      thread-count: 128
      pool-name: 808-msg-processor
      max-pending-tasks: 128
logging:
  level.root: info
  level.io.github.hylexus: info
  level.jt-808.request.decoder: info
  level.jt-808.response.encoder: info
