spring:
  application:
    name: jt-1078-server-sample-webflux-boot3
  profiles:
    active: local
  jackson:
    time-zone: GMT+8

jt1078:
  dump:
    collector-path: /Users/hylexus/tmp/jtt/collector
