server:
  port: 8808
jt808:
  built-components:
    request-handlers:
      enabled: true
    component-statistics:
      enabled: true
  protocol:
    max-frame-length: 1024
  server:
    port: 6808
    boss-thread-count: 0
    worker-thread-count: 0
    idle-state-handler:
      enabled: true
      reader-idle-time: 20m
      writer-idle-time: 20m
      all-idle-time: 20m
  msg-processor:
    thread-pool:
      # core-pool-size: Runtime.getRuntime().availableProcessors() + 1
      # maximum-pool-size: 2 * corePoolSize
      keep-alive-time: 60s
      blocking-queue-size: 100
      thread-name-format: '808-msg-processor-%d'
logging:
  level.root: info
  level.io.github.hylexus: info
  level.jt-808.request.decoder: info
  level.jt-808.response.encoder: info
