server:
  port: 8808
jt808:
  server:
    port: 6808
  built-components:
    component-statistics:
      enabled: true
    request-handlers:
      enabled: false
logging:
  level.root: info
  level.io.github.hylexus: info
  level.jt-808.request.decoder: debug
  level.jt-808.response.encoder: debug
  level.jt-808.command-sender: debug
