server:
  port: 8808
jt808:
  print-component-statistics: true
logging:
  level: info
  level.io.github.hylexus.jt: debug
  level.jt-808.channel: debug
  level.jt-808.request.decoder: debug
  level.jt-808.response.encoder: debug