server:
  port: 8808
logging:
  level: info
  level.io.github.hylexus: info
  level.jt-808.request.decoder: debug
  level.jt-808.response.encoder: debug
jt808:
  print-component-statistics: true
  protocol:
    version: auto_detection
  entity-scan:
    enabled: true
    base-packages: io.github.hylexus.jt808.samples.mixedversion.entity.req
    enable-builtin-entity: true
  converter-scan:
    enabled: true
    base-packages: io.github.hylexus.jt808.samples.mixedversion.converter
  handler-scan:
    enabled: true
    base-packages: io.github.hylexus.jt808.samples.mixedversion.handler
    register-builtin-msg-handlers: true
  server:
    port: 6808
    boss-thread-count: 0
    worker-thread-count: 0
  msg-processor:
    thread-pool:
      core-pool-size: 4
      maximum-pool-size: 4
      keep-alive-time: 60s
      blocking-queue-size: 20
      thread-name-format: '808-msg-processor-%d'
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    servlet:
      content-type: text/html
  jackson:
    time-zone: Asia/Shanghai

