server:
  port: 8808
logging:
  level.root: info
  level.io.github.hylexus: info
  level.jt-808.request.decoder: debug
  level.jt-808.response.encoder: debug
jt808:
  print-component-statistics: true
  built-components:
    request-handlers:
      enabled: true
