server:
  port: 8808
logging:
  level.root: info
  level.io.github.hylexus: info
  level.jt-808.request.decoder: debug
  level.jt-808.response.encoder: debug
jt808:
  built-components:
    component-statistics:
      enabled: true
    request-handlers:
      enabled: true
  protocol:
    max-frame-length: 1024
  server:
    port: 6808
    boss-thread-count: 0
    worker-thread-count: 0
    idle-state-handler:
      enabled: true
      reader-idle-time: 20m
      writer-idle-time: 20m
      all-idle-time: 20m
  msg-processor:
    thread-pool:
      # core-pool-size: Runtime.getRuntime().availableProcessors() + 1
      # maximum-pool-size: 2 * corePoolSize
      keep-alive-time: 60s
      blocking-queue-size: 100
      thread-name-format: '808-msg-processor-%d'
  request-sub-package-storage:
    type: caffeine # caffeine || none
    ## 当且仅当 jt808.request-sub-package-storage.type = caffeine 时生效
    caffeine:
      # 最多缓存多少条消息
      maximum-size: 1024
      # 最大缓存时间
      ttl: 45s
  response-sub-package-storage:
    type: caffeine # caffeine || redis || none
    ## 当且仅当 jt808.response-sub-package-storage.type = caffeine 时生效
    caffeine:
      # 最多缓存多少条消息
      maximum-size: 1024
      # 最大缓存时间
      ttl: 45s
    ## 当且仅当 jt808.response-sub-package-storage.type = redis 时生效
    redis:
      # 最大缓存时间
      ttl: 1m

